services:
  node1:
    build: .
    image: kvs-node
    container_name: node1
    environment:
      - NODE_IDENTIFIER=1
      - PORT=8081
      - HOST=${PUBLIC_HOST}
    ports:
      - "8081:8081"
    networks:
      - kvs-net

  node2:
    build: .
    image: kvs-node
    container_name: node2
    environment:
      - NODE_IDENTIFIER=2
      - PORT=8082
      - HOST=${PUBLIC_HOST}
    ports:
      - "8082:8081"
    networks:
      - kvs-net

  node3:
    build: .
    image: kvs-node
    container_name: node3
    environment:
      - NODE_IDENTIFIER=3
      - PORT=8083
      - HOST=${PUBLIC_HOST}
    ports:
      - "8083:8081"
    networks:
      - kvs-net

networks:
  kvs-net:
    driver: bridge
